# Boolean Array

In [1]:
import numpy as np

h = np.arange(15).reshape((5, 3))
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [2]:
h > 8

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [3]:
(h == 5).astype(int)

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [4]:
h[h>8]

array([ 9, 10, 11, 12, 13, 14])

In [5]:
h[(h>4) & (h <=12)]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
h[(h<4) | (h >= 12)]

array([ 0,  1,  2,  3, 12, 13, 14])

# np.where(condition, if true, else)

In [7]:
np.where(h>7, 1, 0)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [1, 1, 1],
       [1, 1, 1]])