# Array

In [2]:
import array

v = [0.5, 0.75, 1.0, 1.5, 2.0]
a = array.array('f', v)
a
a.append(0.5)
a
a.extend([5.0, 6.75])
a
2 * a
with open('array.apy', 'wb') as f:
    a.tofile(f)

## read the five element from the array file
b = array.array('f')
with open('array.apy', 'rb') as f:
    b.fromfile(f, 5)
b

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])

# Numpy arrays

In [3]:
import numpy as np

a = np.array([0, 0.5, 1.0, 1.5, 2.0], dtype=np.float64)
a.sum()
a.std()
a.cumsum()

array([0. , 0.5, 1.5, 3. , 5. ])

# Universal functions

### operate on ndarray objects as well as on basic python data types.

In [4]:
np.exp(a)
np.sqrt(a)

import math

%timeit np.sqrt(2.5)
%timeit math.sqrt(2.5)

1.04 µs ± 40.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
157 ns ± 11.7 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


# Multiple Dimension

In [5]:
b = np.array([a, a * 2])
b

array([[0. , 0.5, 1. , 1.5, 2. ],
       [0. , 1. , 2. , 3. , 4. ]])

In [6]:
b[0,2] == b[0][2]

True

In [7]:
b.sum(axis=1) # sum per row
b.sum(axis=0) # sum per column
b.sum() # overall sum

15.0

# Create a ndarray instance

one of the way to create array is by using np.array. However, this assumes all elements are available.
Other is to instant ndarray first to populate them later with results.

In [8]:
c = np.zeros((2, 3), dtype='i', order='C')
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [9]:
d = np.ones((2, 3, 4), dtype='i', order='C')
d

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [10]:
# change the ndarray's values to zero then to one

e = np.zeros_like(d, dtype='f', order='C')
e = np.ones_like(e)
e

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

In [11]:
f = np.empty((2, 3, 2))
g = np.empty_like(d) 
g

array([[[1065353216, 1065353216, 1065353216, 1065353216],
        [1065353216, 1065353216, 1065353216, 1065353216],
        [1065353216, 1065353216, 1065353216, 1065353216]],

       [[1065353216, 1065353216, 1065353216, 1065353216],
        [1065353216, 1065353216, 1065353216, 1065353216],
        [1065353216, 1065353216, 1065353216, 1065353216]]], dtype=int32)

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
g = np.linspace(5, 15, 12)
g

array([ 5.        ,  5.90909091,  6.81818182,  7.72727273,  8.63636364,
        9.54545455, 10.45454545, 11.36363636, 12.27272727, 13.18181818,
       14.09090909, 15.        ])

# Reshaping and Resizing

In [14]:
h = np.arange(15)
h

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
i = h.reshape((5, 3))
i

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [16]:
i.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [17]:
i.transpose()

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [18]:
h = h.reshape((5, 3))

In [19]:
# reshaping the ndarray may result into downsizing or upsizing the ndarray
np.resize(h, (6, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14,  0,  1,  2],
       [ 3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4,  5]])

In [20]:
# horizontal stacking
np.hstack((h, 2 * h))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16],
       [ 9, 10, 11, 18, 20, 22],
       [12, 13, 14, 24, 26, 28]])

In [21]:
# vertical stacking
np.vstack((h, 0.2 * h))

array([[ 0. ,  1. ,  2. ],
       [ 3. ,  4. ,  5. ],
       [ 6. ,  7. ,  8. ],
       [ 9. , 10. , 11. ],
       [12. , 13. , 14. ],
       [ 0. ,  0.2,  0.4],
       [ 0.6,  0.8,  1. ],
       [ 1.2,  1.4,  1.6],
       [ 1.8,  2. ,  2.2],
       [ 2.4,  2.6,  2.8]])

# Flattening of ndarray

In [22]:
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [24]:
h.flatten()
h.flatten(order='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
h.flatten(order='F')

array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14])

In [26]:
# ravel is another method for flatten
h.ravel(order='F')

array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14])