# Vectorization Of Code

**Vectorization** is the strategy to get more compact code that is possibly executed faster.

- Apply a function to operate at "**once**", instead by looping over.
- **map()** and **filter()** provide some basic means for vectorization.
- **Numpy** has vectorization built in deep down in its core.

In [13]:
def looping(arg):
    sum = 0
    for i in range(0, arg):
        sum += i

%timeit looping(1000)
%timeit map(looping, [1000])

66.9 µs ± 3.18 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
216 ns ± 14.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# Basic vectorization

In [16]:
# simple addition sum can be example for a vectorization in numpy

import numpy as np

np.random.seed(100)
r = np.arange(12).reshape((4, 3))
s = np.arange(12).reshape((4, 3)) * 0.5

r + s # since it is a element-wise addition as a vectorized operation (no looping)

array([[ 0. ,  1.5,  3. ],
       [ 4.5,  6. ,  7.5],
       [ 9. , 10.5, 12. ],
       [13.5, 15. , 16.5]])

# Broadcasting

In [17]:
# Numpy also supports what is called Broadcasting.
# This allows to combine object within a single operation.

r + 4

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

# Custom-defined Python functions

In [19]:
# if the implementation allows, arrays can be used as int or float objects.

def f(x):
    return 3 * x + 5

f(0.5)
f(r) # element-wise evaluation and vectorization of the function.

array([[ 5,  8, 11],
       [14, 17, 20],
       [23, 26, 29],
       [32, 35, 38]])

### Note: By using these kinds of operation, we simply avoid loops on python level 
###         which is taken care by optimized code, most of it written in C.
###         resulting in faster than pure Python explaining the secret.